### ISSUE TITLE
Is it possible to define a vertically propagating wave field, defining the amplitude of the incident wave not the force parameter?

### ISSUE THREAD

**Issue by Shahram-Maghami** [jpampuero/sem2dpack#3]
Dear developers. 
I am trying to model a sedimentary basin employing SEM2DPack. after struggling with the code for a while, finally, I could make an initial model and analyze it successfully. however, I needed to define the incident as a vertically propagating wave field, representing a far-field earthquake in consistency with the elastic behavior of defined materials. Thanks to the manual of the code I could define the desired wave-field through multiple point sources. This way, the incident should be defined as the "FORCE" parameter. when I change the incident in the same model to be  "WAVE", it behaves as a single point source. because I want my analysis to be comparable with other methods I have adopted, I prefer to define the amplitude of the wave as the input. Is it somehow possible?
I have attached some examples. 
![0](https://user-images.githubusercontent.com/48868554/68757533-5819e180-0621-11ea-84f1-9f006abf3e01.JPG)

![1-1](https://user-images.githubusercontent.com/48868554/68757137-aa0e3780-0620-11ea-86fc-d7cf7cf3f71d.JPG)
![4](https://user-images.githubusercontent.com/48868554/68757155-b4303600-0620-11ea-8956-ed7b2e4ffba6.JPG)

**Comment by jpampuero** [comment]
I am not sure I understand your question. But if you are asking how to set a vertical incident wave, here is my answer:
Please read in the manual the definition of the "angle" parameter in SRC_WAVE. In particular, "normal incidence from below if angle=0". You have set angle=90, which is horizontal incidence, not vertical.

**Comment by elifo** [comment]
Hi Shahram,

To mimic a vertically incident plane wave, you should define correctly both 'boundary conditions' and 'source conditions', and using 'tabulated stf' option allows you to insert your own velocity-time histories. 

My suggestions for sedimentary basin simulations in far field are listed below.

Source conditions:
* define 'WAVE' mechanism in SRC_DEF line (instead of multiple point sources);
* define incidence angle (angle=0 for vertical incidence) and phase;
* use tabulated source-time function by setting stf='TAB' in SRC_DEF line;
* define file name in STF_TAB line. This file should contain two columns: time and velocity amplitude.

Boundary conditions:
* bottom: absorbing boundary (let_wave=True; Stacey=False);
* side boundaries: periodic (you should verify that model is sufficiently long to avoid unwanted reflections; and your mesh should be appropriately created for two sides to overlap);
* free surface.
